# Generated by Django 6.0.7 on 2026-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB - Российский рубль'), ('usd', 'USD - Доллар США')], default='usd', max_length=3, verbose_name='Валюта'),
        ),
    ]
